### ISSUE TITLE
Which field to use for invoice number

### ISSUE THREAD

**Issue by kowabungaboy** [bitmarck-service/validator-configuration-diga#15]
Hi,

some insurances rejected our correct validated invoices due to missing an invoice number. Which field should be used to provide an invoice number without breaking the validation?

Thanks in advance and kind regards

**Comment by marcusfey** [comment]
Please refer to the related rule:
https://github.com/bitmarck-service/validator-configuration-diga/blob/e85e62865baf83d0a7a738ef1669e8302504967d/src/main/schematron/dre0.sch#L24

Here is an example: https://github.com/bitmarck-service/validator-configuration-diga/blob/e85e62865baf83d0a7a738ef1669e8302504967d/src/test/resources/dre0/xrechnung-2.0-richtig.xml#L29

ExchangedDocument -> ID is the relevant element

**Comment by kowabungaboy** [comment]
Hi,

thanks a lot, submission worked and everything validated correctly.

Kind regards
